image: Visual Studio 2017

clone_folder: c:\projects\USDPackages

branches:
    only:
        - gbk

platform:
    - x64

install:
    - ps: $env:USD_YY_VERSION = (Get-Content .\cmake\defaults\Version.cmake | Where-Object {$_ -match 'PXR_MINOR_VERSION'}).Split("( )")[2].Trim('"').PadLeft(2, "0")
    - ps: $env:USD_MM_VERSION = (Get-Content .\cmake\defaults\Version.cmake | Where-Object {$_ -match 'PXR_PATCH_VERSION'}).Split("( )")[2].Trim('"').PadLeft(2, "0")
    - ps: Update-AppveyorBuild -Version "$env:USD_YY_VERSION.$env:USD_MM_VERSION-$env:APPVEYOR_REPO_BRANCH-build$env:APPVEYOR_BUILD_NUMBER"

cache:
    - C:\USDgen\build\boost -> build_scripts/build_usd.py
    - C:\USDgen\build\IlmBase -> build_scripts/build_usd.py
    - C:\USDgen\build\OpenEXR -> build_scripts/build_usd.py
    - C:\USDgen\build\OpenSubdiv-3_1_1 -> build_scripts/build_usd.py
    - C:\USDgen\build\zlib-1.2.11 -> build_scripts/build_usd.py
    - C:\USDgen\src -> build_scripts/build_usd.py

init:
    - set PATH=c:/Python27-x64;c:/Python27-x64/Scripts;%PATH%
    - C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Community\VC\Auxiliary\Build\vcvarsall.bat amd64


before_build:
    - python -m pip install --upgrade pip
    - pip install pyside
    - pip install PyOpenGL
    - git clone --single-branch --branch gbk  https://github.com/goodbyekansas/USD c:/projects/USD
    - git clone --single-branch --branch gbk-master https://github.com/goodbyekansas/maya-usd c:/projects/maya-usd
    - wget https://autodesk-adn-transfer.s3-us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2019/Autodesk_Maya_2019_2_Update_DEVKIT_Windows.zip -OutFile devkit_maya2019.zip
    - echo "extracting maya devkit 2019 archive..."
    - Expand-Archive -Path devkit_maya2019.zip -DestinationPath c:/USDgen/src/devkit_maya2019 -Force
    - wget https://s3-us-west-2.amazonaws.com/autodesk-adn-transfer/ADN+Extranet/M%26E/Maya/devkit+2018/Autodesk_Maya_2018_6_Update_DEVKIT_Windows.zip -OutFile devkit_maya2018.zip
    - echo "extracting maya devkit 2018 archive..."
    - Expand-Archive -Path devkit_maya2018.zip -DestinationPath C:/USDgen/src/devkit_maya2018 -Force

  

build_script:

    - cd c:/projects/USD
    - python build_scripts/build_usd.py -vvv --build c:/USDgen/build --src c:/USDgen/src c:/USDinst/USD-core
    - cd c:/USDgen/build
    - dir
    - cd c:/projects/maya-usd
    - python build.py -v 3 --pxrusd-location c:/USDinst/USD-core --build-args="-DSKIP_USDMAYA_TESTS=ON,-DUFE_INCLUDE_DIR=c:/USDgen/src/devkit_maya2019/devkitBase/devkit/ufe/include,-DUFE_LIBRARY=c:/USDgen/src/devkit_maya2019/devkitBase/devkit/ufe/lib,-DMAYA_INCLUDE_DIRS=c:/USDgen/src/devkit_maya2019/devkitBase/include"  --install-location c:/Usdinst/maya-usd-2019 /tmp/workspace_maya2019 --devkit-location=c:/USDgen/src/devkit_maya2019/devkitBase/devkit
    - python build.py -v 3 --pxrusd-location c:/USDinst/USD-core --build-args="-DSKIP_USDMAYA_TESTS=ON,-DUFE_INCLUDE_DIR=c:/USDgen/src/devkit_maya2018/devkitBase/devkit/ufe/include,-DUFE_LIBRARY=c:/USDgen/src/devkit_maya2018/devkitBase/devkit/ufe/lib,-DMAYA_INCLUDE_DIRS=c:/USDgen/src/devkit_maya2018/devkitBase/include"  --install-location c:/Usdinst/maya-usd-2018 /tmp/workspace_maya2018 --devkit-location=c:/USDgen/src/devkit_maya2018/devkitBase/devkit
